/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-04-06 06:06:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.proMovie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class proMovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("\tGravity by Pixelarity\n");
      out.write("\tpixelarity.com | hello@pixelarity.com\n");
      out.write("\tLicense: pixelarity.com/license\n");
      out.write("-->\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Untitled</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("\t</head>\n");
      out.write("\t<style>\n");
      out.write("\t\t.searchZone {\n");
      out.write("\t\t\twidth:70%;\n");
      out.write("\t\t\tmargin-left: auto !important;\n");
      out.write("\t\t\tmargin-right: auto !important;\n");
      out.write("\t\t}\n");
      out.write("\t\t.oneLine1 {\n");
      out.write("\t\t\twidth:30% !important;\n");
      out.write("\t\t}\n");
      out.write("\t\t.oneLine2 {\n");
      out.write("\t\t\twidth:50% !important;\n");
      out.write("\t\t}\n");
      out.write("\t\t.searchBtn {\n");
      out.write("\t\t\twidth:20% !important;\n");
      out.write("\t\t}\n");
      out.write("\t\t.row > .col-poster {\n");
      out.write("\t\t\twidth: 25%;\n");
      out.write("\t\t}\n");
      out.write("\t\t.pagingTable {\n");
      out.write("\t\t\twidth:50%;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t@media screen and (max-width: 736px) {\n");
      out.write("\t\t\t.searchZone {\n");
      out.write("\t\t\t\twidth:100%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.oneLine1{\n");
      out.write("\t\t\t\twidth:100% !important;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.oneLine2{\n");
      out.write("\t\t\t\twidth:100% !important;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.searchBtn {\n");
      out.write("\t\t\t\twidth:100% !important;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.row > .col-poster {\n");
      out.write("\t\t\twidth: 33.33333%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.pagingTable {\n");
      out.write("\t\t\t\twidth:100%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</style>\n");
      out.write("\t<body class=\"is-preload\">\n");
      out.write("\n");
      out.write("\t\t<!-- Header -->\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../header.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Main -->\n");
      out.write("\t\t\t<section id=\"main\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<header class=\"major\">\n");
      out.write("\t\t\t\t\t\t<h2>독립영화 모아보기</h2>\n");
      out.write("\t\t\t\t\t\t<p>독립영화 정보 확인 페이지</p>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Content -->\n");
      out.write("\t\t\t\t\t<section id=\"content\">\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t\t\t<!-- 영화리스트 이미지 출력 -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- 버튼 선택 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"actions small\" style=\"margin-left:auto; margin-right:auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button alt small\">지난 상영</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button primary small\">현재 상영</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button alt small\">상영 예정</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- 검색창 -->\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row gtr-uniform gtr-50\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row gtr-uniform gtr-50 searchZone\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-6 col-12-small oneLine1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"category\" id=\"category\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">영화 제목</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">감독명</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-6 col-12-small oneLine2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" value=\"\" placeholder=\"검색어\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-3 col-6-large col-12-medium searchBtn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions stacked\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button alt small fit\">검색</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- 포스터 이미지 출력 -->\n");
      out.write("\t\t\t\t\t\t\t<fieldset style=\"border:none;\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box alt\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row gtr-50 gtr-uniform\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 반복문 시작 -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-poster\" onclick=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom:4px;\" onmouseover=\"\" onmouseout=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/testImage.jpg\" alt=\"\" style=\"border-radius: 10px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\" style=\"padding:5px; display:none; position: absolute; top:0; left:0; bottom:0; right:0; color:white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>가나다라마바사아자차카타파하가나다라마바사아자차카타파</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><strong>어벤저스 엔드게임</strong></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 반복문 끝 -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<!-- Footer -->\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../footer.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/jquery.poptrox.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"assets/js/main.js\"></script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script src=\"//code.jquery.com/jquery-3.5.1.min.js\" ></script>\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\t$('.posterTag').on('mouseover', function(){\n");
      out.write("\t\t\t\t\t$(this).children('#detailText').css('display', 'block');\n");
      out.write("\t\t\t\t\t$(this).children('#detailText').toggleClass(\"on\");\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$('.posterTag').on('mouseout', function(){\n");
      out.write("\t\t\t\t\t$(this).children('#detailText').css('display', 'none');\n");
      out.write("\t\t\t\t\t$(this).children('#detailText').toggleClass(\"on\");\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
