/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-04-14 02:32:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("fieldset {\r\n");
      out.write("\tborder-radius: 7%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding-right: 0%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".poster {\r\n");
      out.write("\tborder: dotted;\r\n");
      out.write("\t/* width: 100%;\r\n");
      out.write("\theight: 70%; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image.fit {\r\n");
      out.write("\tmargin: 0 0;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 480px) {\r\n");
      out.write("\t.button {\r\n");
      out.write("\t\tpadding: 0 32px !important;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../header.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t<h2>게시글 작성</h2>\r\n");
      out.write("\t\t\t\t<p>작성된 게시글은 자유 게시판에 등록됩니다.</p>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Text -->\r\n");
      out.write("\t\t\t\t<div class=\"col-8 col-10-medium col-12-small\" style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t<fieldset\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: solid; border-style: outset; padding-left: 4%; padding-top: 4%; padding-bottom: 4%; padding-right: 4%;\">\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<section style=\"margin-right: auto; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardWriteOk.bo\" method=\"post\" name=\"boardForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"photos\" style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4 col-3-small photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; margin-right: auto; margin-left: auto; width: 40%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"poster image fit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding-left: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"firstImg\" class=\"img\" alt=\"\" src=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: none; width: 100%; height: 100%;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"span1\" class=\"image fit\" style=\"padding-bottom: 30%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"first-file-input\"> <img id=\"firstImg2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"camera\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/add.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"영화 포스터\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 50px; margin: 47% auto auto auto; cursor: pointer;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"boardImage1\" id=\"first-file-input\" type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"preview1()\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"delete1()\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4 col-3-small photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; margin-right: auto; margin-left: auto; width: 40%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"poster image fit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding-left: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"secondImg\" alt=\"\" src=\"\" class=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: none; width: 100%; height: 100%;\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"span2\" class=\"image fit\" style=\"padding-bottom: 30%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"second-file-input\"> <img id=\"secondImg2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"camera\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/add.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"영화 포스터\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 50px; margin: 47% auto auto auto; cursor: pointer;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"boardImage2\" id=\"second-file-input\" type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"preview2()\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"delete2()\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4 col-3-small photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; margin-right: auto; margin-left: auto; width: 40%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"poster image fit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding-left: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"thirdImg\" alt=\"\" src=\"\" class=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: none; width: 100%; height: 100%;\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"span3\" class=\"image fit\" style=\"padding-bottom: 30%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"third-file-input\"> <img id=\"thirdImg2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"camera\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/add.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"영화 포스터\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 50px; margin: 47% auto auto auto; cursor: pointer;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"boardImage3\" id=\"third-file-input\" type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"preview3()\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"delete3()\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>문구입력</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"boardContent\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; resize: none; margin-left: auto; margin-right: auto; margin-bottom: 1%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"count\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"current_count\">0</span> <span id=\"maximum_count\">/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t50</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript: boardForm.submit();\" class=\"button\" style=\"float: right;\">업로드</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../footer.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.poptrox.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction preview1() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tfirstImg.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("\t\t\tfirstImg.style.display = \"block\";\r\n");
      out.write("\t\t\tfirstImg.style.objectFit = \"cover\";\r\n");
      out.write("\t\t\tspan1.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction preview2() {\r\n");
      out.write("\t\t\tif (window.getComputedStyle(firstImg).display == \"block\") {\r\n");
      out.write("\t\t\t\tsecondImg.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("\t\t\t\tsecondImg.style.display = \"block\";\r\n");
      out.write("\t\t\t\tsecondImg.style.objectFit = \"cover\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tspan2.style.display = \"none\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"첫번째 앨범을 채워주세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction preview3() {\r\n");
      out.write("\t\t\tif (window.getComputedStyle(secondImg).display == \"block\") {\r\n");
      out.write("\t\t\t\tthirdImg.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("\t\t\t\tthirdImg.style.display = \"block\";\r\n");
      out.write("\t\t\t\tthirdImg.style.objectFit = \"cover\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tspan3.style.display = \"none\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"두번째 앨범을 채워주세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction delete1() {\r\n");
      out.write("\t\t\tfirstImg.style.display = \"none\";\r\n");
      out.write("\t\t\tspan1.style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction delete2() {\r\n");
      out.write("\t\t\tsecondImg.style.display = \"none\";\r\n");
      out.write("\t\t\tspan2.style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction delete3() {\r\n");
      out.write("\t\t\tthirdImg.style.display = \"none\";\r\n");
      out.write("\t\t\tspan3.style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$('textarea')\r\n");
      out.write("\t\t\t\t.keyup(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar characterCount = $(this).val().length, current_count = $('#current_count'), maximum_count = $('#maximum_count'), count = $('#count');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tcurrent_count.text(characterCount);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
