/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-04-08 06:56:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("\tGravity by Pixelarity\r\n");
      out.write("\tpixelarity.com | hello@pixelarity.com\r\n");
      out.write("\tLicense: pixelarity.com/license\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>인디프로젝트</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<!-- 슬라이드 css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://unpkg.com/swiper@6.5.0/swiper-bundle.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".searchZone {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\tmargin-left: auto !important;\r\n");
      out.write("\tmargin-right: auto !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".oneLine2 {\r\n");
      out.write("\twidth: 80% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchBtn {\r\n");
      out.write("\twidth: 20% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row>.col-poster {\r\n");
      out.write("\twidth: 16.66666%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagingTable {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".swiper-container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-slide {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\t/* Center slide text vertically */\r\n");
      out.write("\tdisplay: -webkit-box;\r\n");
      out.write("\tdisplay: -ms-flexbox;\r\n");
      out.write("\tdisplay: -webkit-flex;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\t-webkit-box-pack: center;\r\n");
      out.write("\t-ms-flex-pack: center;\r\n");
      out.write("\t-webkit-justify-content: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\t-webkit-box-align: center;\r\n");
      out.write("\t-ms-flex-align: center;\r\n");
      out.write("\t-webkit-align-items: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".leftBtn {\r\n");
      out.write("\tbackground-color: rgb(0 0 0/ 5%);\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rightBtn {\r\n");
      out.write("\tbackground-color: rgb(0 0 0/ 5%);\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnMouseOver {\r\n");
      out.write("\tbackground-color: rgb(0 0 0/ 43%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".poptrox-popup .closer:before {\r\n");
      out.write("\tright: 0px !important;\r\n");
      out.write("\ttop: 0px !important;\r\n");
      out.write("\tz-index:9999 !important;\r\n");
      out.write("}\r\n");
      out.write(".poptrox-popup .closer {\r\n");
      out.write("\tz-index: 9999;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tright: 0px !important;\r\n");
      out.write("}\r\n");
      out.write(".poptrox-popup {\r\n");
      out.write("\ttop:25px;\r\n");
      out.write("\tpadding-bottom:0 !important;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".caption {\r\n");
      out.write("\tdisplay:none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic{\r\n");
      out.write("        \tline-height:0 !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".floating { position: fixed; right: 50%; top: 180px; margin-right: -720px; text-align:center; width: 120px; }\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 683px) {\r\n");
      out.write("\t.searchZone {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.oneLine1 {\r\n");
      out.write("\t\twidth: 100% !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.oneLine2 {\r\n");
      out.write("\t\twidth: 100% !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.searchBtn {\r\n");
      out.write("\t\twidth: 100% !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row>.col-poster {\r\n");
      out.write("\t\twidth: 33.33333%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pagingTable {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.image{\r\n");
      out.write("\t\twidth:80%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.col-poster{\r\n");
      out.write("\t\tmargin-left: auto !important;\r\n");
      out.write("\t\tmargin-right: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 480px) {\r\n");
      out.write("\tiframe {\r\n");
      out.write("\t\tmax-width: 330px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.image{\r\n");
      out.write("\t\twidth:40%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.col-poster{\r\n");
      out.write("\t\tmargin-left: auto !important;\r\n");
      out.write("\t\tmargin-right: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../header.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t<h2>자유게시판</h2>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t\t<div id=\"gallery\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 검색창 -->\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row gtr-uniform gtr-50\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row gtr-uniform gtr-50 searchZone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6 col-12-small oneLine2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"#\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-3 col-6-large col-12-medium searchBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions stacked\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" data-poptrox=\"ignore\" class=\"button alt small fit\">검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-3 col-6-large col-12-medium searchBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions stacked\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardWrite.bo\" data-poptrox=\"ignore\" class=\"button small fit\">게시글 작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- 포스터 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\" style=\" width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-poster\" style=\"width:30%; height:10%; margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image fit posterTag\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/testImage.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"detailText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 5px; display: none; position: absolute; top: 0; left: 0; bottom: 0; right: 0; color: white; background-color: rgba(0, 0, 0, 0.69); border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"button primary small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardView.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-poptrox=\"iframe,800x500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:80%; height:100%; background:transparent;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.poptrox.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 슬라이드 js -->\r\n");
      out.write("\t<script src=\"https://unpkg.com/swiper@6.5.0/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.posterTag').on('mouseover', function(){\r\n");
      out.write("\t\t\t//event.stopPropagation();\r\n");
      out.write("\t\t\t$(this).children('#detailText').css('display', 'block');\r\n");
      out.write("\t\t\t$(this).children('#detailText').toggleClass(\"on\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.posterTag').on('mouseout', function(){\r\n");
      out.write("\t\t\t$(this).children('#detailText').css('display', 'none');\r\n");
      out.write("\t\t\t$(this).children('#detailText').toggleClass(\"on\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('.moveBtn').on('mouseover', function(){\r\n");
      out.write("\t\t\t$(this).toggleClass(\"btnMouseOver\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('.moveBtn').on('mouseout', function(){\r\n");
      out.write("\t\t\t$(this).toggleClass(\"btnMouseOver\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.detailText').on('click', function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(window.matchMedia('(max-width: 736px)').matches){}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar swiper = new Swiper('.swiper-container', {\r\n");
      out.write("\t\t\tspaceBetween : 10,\r\n");
      out.write("\t\t\tloop : false,\r\n");
      out.write("\t\t\tloopFillGroupWithBlank : true,\r\n");
      out.write("\t\t\tallowTouchMove: false,\r\n");
      out.write("\t\t\tpagination : {\r\n");
      out.write("\t\t\t\tel : '.swiper-pagination',\r\n");
      out.write("\t\t\t\tclickable : true,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tnavigation : {\r\n");
      out.write("\t\t\t\tnextEl : '.swiper-button-next',\r\n");
      out.write("\t\t\t\tprevEl : '.swiper-button-prev',\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbreakpoints : { // 반응형 설정이 가능 width값으로 조정\r\n");
      out.write("\t\t\t\t768: {\r\n");
      out.write("\t\t\t\t\tslidesPerView : 5,\r\n");
      out.write("\t\t\t\t\tslidesPerGroup : 5\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t1: {\r\n");
      out.write("\t\t\t\t\tslidesPerView : 3,\r\n");
      out.write("\t\t\t\t\tslidesPerGroup : 3\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//poptrox\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#gallery').poptrox({\r\n");
      out.write("\t\t\t\tusePopupCaption : true,\r\n");
      out.write("\t\t\t\tusePopupNav : true,\r\n");
      out.write("\t\t\t\tpopupPadding : 0\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
