/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-04-16 06:12:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1618551653000L));
    _jspx_dependants.put("jar:file:/Users/heekng/coding/unityTeam/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/indieProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Untitled</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\n");
      out.write("\t\t<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t<style>\n");
      out.write("\t\n");
      out.write("\t#kakao-login-btn{\n");
      out.write("\t\tmargin-right:auto;\n");
      out.write("\t\tmargin-left:auto;\n");
      out.write("\t\twidth:57%;\n");
      out.write("\t}\n");
      out.write("\t\t fieldset{\n");
      out.write("\t\t   border-radius: 7% ;\n");
      out.write("\t\t  \tmargin:0 auto ;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t@media screen and (max-width:480px) {\n");
      out.write("\t\t\t.button {\n");
      out.write("\t\t\t\twidth: 9.2em !important;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tp {\n");
      out.write("\t\t\t\tfont-size:0.9em !important;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</style>\n");
      out.write("\t<body class=\"is-preload\">\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<!-- Header -->\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../header.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Main -->\n");
      out.write("\t\t\t<section id=\"main\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<header class=\"major\">\n");
      out.write("\t\t\t\t\t\t<h2>로그인</h2>\n");
      out.write("\t\t\t\t\t\t<p>IndieProject 서비스 이용을 위해 로그인 하시길 바랍니다.</p>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Content -->\n");
      out.write("\t\t\t\t\t<section id=\"content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row gtr-uniform gtr-50\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6 col-9-medium col-12-small\" style=\"margin:auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset class=\"fieldset\" style=\"border: solid; border-style: outset; padding-left: 5%; padding-top: 3%; ppadding-right: 0%;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home.me\" name=\"loginForm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>아이디</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input style=\"width:94%; margin-bottom: 15px;\" type=\"text\" name=\"memberId\" id=\"memberId\" placeholder=\"ID\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>비밀번호</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input style=\"width:94%;\" type=\"password\" name=\"memberPw\" id=\"memberPw\" placeholder=\"PASSWORD\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"text-align: left; margin-top:3rem;\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/FindIdPwOk.me\">아이디 / 비밀번호 찾기</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:94%; margin-top:2rem; text-align:center;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a style=\"width:10em;\" href=\"javascript:primaryLogin();\" class=\"button\">로그인</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a style=\"width:10em;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/SignUp.me\" class=\"button alt\">회원가입</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"image\" style=\"width:94%;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<a id=\"kakao-login-btn\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"http://developers.kakao.com/logout\"></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<!-- Footer -->\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/../footer.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script>var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";</script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.poptrox.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t      // 사용할 앱의 JavaScript 키를 설정해 주세요.\n");
      out.write("\t\t      Kakao.init('d9a10e4883f95c7fd5c17d1e96917a3f');\n");
      out.write("\t\t      // 카카오 로그인 버튼을 생성합니다.\n");
      out.write("\t\t      Kakao.Auth.createLoginButton({\n");
      out.write("\t\t        container: '#kakao-login-btn',\n");
      out.write("\t\t        success: function(authObj) {\n");
      out.write("\t\t          // 로그인 성공시, API를 호출합니다.\n");
      out.write("\t\t          Kakao.API.request({\n");
      out.write("\t\t            url: '/v2/user/me',\n");
      out.write("\t\t            success: function(res) {\n");
      out.write("\t\t         \n");
      out.write("\t\t              $.ajax({\n");
      out.write("\t\t\t\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\t\t\t\turl:contextPath + \"/member/MemberLoginOk.me?kakaoId=\"+JSON.stringify(res.id)+\"&kakaoName=\"+res.properties.nickname,\n");
      out.write("\t\t\t\t\t\t\tdataType: \"text\",\n");
      out.write("\t\t\t\t\t\t    success:function(result){\n");
      out.write("\t\t\t\t\t\t    \tif(result.trim() == \"success\"){\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"세션저장 성공\");\n");
      out.write("\t\t\t\t\t\t              loginForm.submit();\n");
      out.write("\t\t\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"세션저장 실패\");\n");
      out.write("\t\t\t\t\t\t\t\t\tvar id = result.split(\",\")[0];\n");
      out.write("\t\t\t\t\t\t\t\t\tvar name = result.split(\",\")[1];\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(id + \" kid\");\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(name + \" kname\");\n");
      out.write("\t\t\t\t\t\t\t\t\twindow.location.href = contextPath+\"/member/kakaoSignup.me?id=\"+id+\"&name=\"+name;\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t    },\n");
      out.write("\t\t\t\t\t\t    error:function(data){\n");
      out.write("\t\t\t\t\t\t    \t  console.log(data);\n");
      out.write("\t\t\t\t\t\t    \tconsole.log(\"로그인안됨\");\n");
      out.write("\t\t\t\t\t\t    }\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t            },\n");
      out.write("\t\t            fail: function(error) {\n");
      out.write("\t\t              alert(JSON.stringify(error));\n");
      out.write("\t\t            }\n");
      out.write("\t\t          });\n");
      out.write("\t\t        },\n");
      out.write("\t\t        fail: function(err) {\n");
      out.write("\t\t          alert(JSON.stringify(err));\n");
      out.write("\t\t        }\n");
      out.write("\t\t      });\n");
      out.write("\t\t\t\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\tfunction primaryLogin(){\n");
      out.write("\t\t\t\tvar memberId = $(\"input[name='memberId']\").val();\n");
      out.write("\t\t\t\tvar memberPw = $(\"input[name='memberPw']\").val();\n");
      out.write("\t\t\t\tif(memberId==\"\"){\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력해주세요\");\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse if(memberPw==\"\"){\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력해주세요\");\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\turl : contextPath + \"/member/MemberLoginOk.me\",\n");
      out.write("\t\t\t\t\t\ttype:\"post\",\n");
      out.write("\t\t\t\t\t\tdata:({\"memberId\":memberId,\"memberPw\":memberPw}),\n");
      out.write("\t\t\t\t\t\tdataType:\"text\",\n");
      out.write("\t\t\t\t\t\tsuccess : function(result){\n");
      out.write("\t\t\t\t\t\t\tif(result.trim() == \"primaryLoginSuccess\"){\n");
      out.write("\t\t\t\t\t              if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${to}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"\"){\n");
      out.write("\t\t\t\t\t            \tloginForm.submit();\n");
      out.write("\t\t\t\t\t              }else if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${to}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"board\"){\n");
      out.write("\t\t\t\t\t            \tlocation.replace(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/Board.bo\");\n");
      out.write("\t\t\t\t\t              }else if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${to}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"amaDetail\"){\n");
      out.write("\t\t\t\t\t            \t  location.replace(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/amaMovie/AmaMovieDetail.ama?amaNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amaNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t\t\t\t              }else if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${to}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"amaWatch\"){\n");
      out.write("\t\t\t\t\t            \t  location.replace(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/amaMovie/AmaMovieWatch.ama?amaNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amaNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t\t\t\t              }\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\t\talert(\"아이디 또는 비밀번호를 다시 확인해주세요.\");\n");
      out.write("\t\t\t\t\t\t\t\t $(\"input[name='memberId']\").val(\"\");\n");
      out.write("\t\t\t\t\t\t\t\t $(\"input[name='memberPw']\").val(\"\");\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\terror:function(){\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"오류\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /app/member/login.jsp(36,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("to");
      // /app/member/login.jsp(36,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${to}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /app/member/login.jsp(37,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("amaNum");
      // /app/member/login.jsp(37,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amaNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
